### ISSUE TITLE
Metamask

### ISSUE THREAD

**Issue by flamelxyz** [fazelpejmanfar/nft-minting-dapp#1]
Hey, when I click to minting Metamask not opening.

**Comment by SolNFTs** [comment]
Check the console of browser for error

**Comment by flamelxyz** [comment]
> Check the console of browser for error

https://super-wildflower-4967.on.fleek.co/ 

Can you check what is goin on?

**Comment by fazelpejmanfar** [comment]
> > Check the console of browser for error
> 
> https://super-wildflower-4967.on.fleek.co/
> 
> Can you check what is goin on?

cant open it

**Comment by officialsupport-ui** [comment]
Kindly get in touch to get this issue resolved
