### ISSUE TITLE
Error Mint Polygon MATIC 

### ISSUE THREAD

**Issue by DystopianCatsSociety** [fazelpejmanfar/nft-minting-dapp#2]
It has a problem in the matic polygon network even changing values of (network, ID, ABI, and gas fee) etc etc gives Mint error, when adjusting the gas from metamask sometimes it does the Mint

**Comment by fazelpejmanfar** [comment]
in app.js line 312 replace this 
```
        gasLimit: String(totalGasLimit),
        to: CONFIG.CONTRACT_ADDRESS,
        from: blockchain.account,
        value: price,
```

to this          
```
        gasLimit: String(totalGasLimit),
        maxPriorityFeePerGas: null,
        maxFeePerGas: null,
        to: CONFIG.CONTRACT_ADDRESS,
        from: blockchain.account,
        value: price,
```

**Comment by DystopianCatsSociety** [comment]
> 
![Sin título](https://user-images.githubusercontent.com/110140517/185520318-59324dae-45d5-4093-b3cc-9004abb9f767.png)
The problem is not solved, it continues to give an error on mainnet
